on:
  push:
  pull_request:

name: check

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get install --yes espeak sox libmidi-perl

      - name: Install Math::FFT
        run: sudo perl -MCPAN -e 'install Math::FFT'

      - name: Install dependencies to build examples
        run: sudo apt-get install --yes abcmidi

      #- name: Remove the 'clean' step in the Makefile
      #  run: |
      #    head -n -4 examples/Makefile > Makefile 
      #    mv Makefile examples/Makefile
      #    cat examples/Makefile

      - name: Remove the 'clean' step in the Perl script
        run: sed -i 's/delete .self->.opus.;/# Removed by richelbilderbeek/g' ecantorix.pl

      - name: Build examples
        run: |
          cd examples
          make
          cd ..

      - name: run
        run: perl ecantorix.pl -O mmp -o foo.mmp examples/entchen.mid
